const express = require('express');
const router = express.Router();

const {checkToken} = require('../guards/tokenGuard');
const pages = require('./pages');
const auth = require('./auth');
const uploads = require('./uploads');
const parser = require('./parser');
const duration = require('./duration');
const library = require('./library');
const invite = require('./invite');
const downloads = require('./downloads');
const forgot_password = require('./forgot_password');
const errorHandler = require('./errorHandler');
const channel = require('./channels');
const users = require('./users');
const shared = require('./shared');
const preview = require('./preview');
const playlist = require('./playlist');
const contacts = require('./contacts');
const deleted = require('./deleted');
const counterSmartView = require('./counterSmartView');
const colors = require('./colors');
const cards = require('./cards');
const columns = require('./columns');
const components = require('./components');
const tags = require('./tags');
const smartview = require('./smartview');
const libraryComponent = require('./libraryComponents');
const linkPages = require('./linkPages');
const inbox = require('./inbox');
const outbox = require('./outbox');
const playlistManager = require('./playlistManager');
const emoji = require('./emoji');
const {settingsRouter} = require('./settings');
const {cropRouter} = require('./crop');
const {muxRouter} = require('./mux');
const {muxGuard} = require('../guards/muxGuard');

router.use('/page', pages);
router.use('/', auth);
router.use('/component', checkToken, components);
router.use('/emoji', checkToken, emoji);
router.use('/upload', checkToken, uploads);
router.use('/parser', checkToken, parser);
router.use('/library', checkToken, library);
router.use('/download', downloads);
router.use('/duration', duration);
router.use('/invite', invite);
router.use('/forgot_password', forgot_password);
router.use('/error_handler', errorHandler);
router.use('/channels', checkToken, channel);
router.use('/counter_smart_view', checkToken, counterSmartView);
router.use('/users', users);
router.use('/shared', shared);
router.use('/preview', checkToken, preview);
router.use('/inbox', checkToken, inbox);
router.use('/outbox', checkToken, outbox);
router.use('/playlist', playlist);
router.use('/contacts', checkToken, contacts);
router.use('/deleted', checkToken, deleted);
router.use('/color', checkToken, colors);
router.use('/card', checkToken, cards);
router.use('/column', checkToken, columns);
router.use('/tag', checkToken, tags);
router.use('/smartview', checkToken, smartview);
router.use('/library_component', checkToken, libraryComponent);
router.use('/link_page', checkToken, linkPages);
router.use('/playlist_manager', checkToken, playlistManager);
router.use('/settings', checkToken, settingsRouter);
router.use('/crop', checkToken, cropRouter);
router.use('/mux', muxGuard, muxRouter);
module.exports = {router};
