name: Development (Nightly)

on:
  push:
    branches:
      - develop
  workflow_dispatch:

permissions: write-all

jobs:
  build_and_deploy:
    name: Build & Push
    uses: SkillPass/skillpass-backend/.github/workflows/base.yaml@develop
    with:
      environment: dev
      display_env: Development
    secrets: inherit
