name: Production

on:
  push:
    branches:
      - main
    tags:
      - "*"
  workflow_dispatch:

permissions: write-all

jobs:
  build_and_deploy:
    name: Build & Push
    uses: vlgavrilov/action_for_cicd/.github/workflows/base.yaml@main
    with:
      environment: prod
      display_env: Production
    secrets: inherit
